---
- hosts: rbnode1.dev
  tasks:
    - name: Installs git on server
      apt:
         name: "{{ item }}"
         state: present
         update_cache: yes
         cache_valid_time: 3600
      with_items:
        - git
