---
- hosts: rbnode1.dev
  tasks:
    - name: Installs environment packages on server
      apt:
         name: "{{ item }}"
         state: present
         update_cache: yes
         cache_valid_time: 3600
      with_items:
        - vim
        - git
        - nodejs
        - build-essential
        - npm
